env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - plugin:prettier/recommended
ignorePatterns:
  - dist/
  - node_modules/
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'react-refresh'
rules:
  quotes:
    - error
    - single
  semi:
    - error
    - never
  indent:
    - error
    - 2
  object-curly-spacing:
    - error
    - always
  max-len:
    - error
    - 80
  '@typescript-eslint/no-unused-vars': off
  prettier/prettier:
    - error
    - {
        singleQuote: true,
        trailingComma: 'all',
        printWidth: 80,
        tabWidth: 2,
        semi: false,
    }
